[Badges]
; Format: Label = Color | Value (omit Value for dynamic GitHub stats)
Platform = blue | Windows 11
Since = orange
Location = green | Chennai
Commits = blueviolet
Gists = yellow
Repos = red
CPU = brightgreen | i7-9750H
RAM = blue | 16GB
Shell = yellowgreen | pwsh7

[Projects]
; Format: RepositoryName = Description
WinAutoScroll = lightweight global middle-click auto-scrolling on windows.
pwsh-modules = my public pwsh modules and script repo.
windodge.py = poor man's multiple monitors.
scoop_bucket = personal bucket of stuff i use not found in other buckets.
